package com.companion.android

const val SIGN_UP_FRAGMENT: String = "SIGN_UP_FRAGMENT"
const val LOG_IN_FRAGMENT: String = "LOG_IN_FRAGMENT"
const val FORGOT_PASSWORD_EMAIL_FRAGMENT: String = "FORGOT_PASSWORD_EMAIL_FRAGMENT"
const val FORGOT_PASSWORD_NEW_PASSWORD_FRAGMENT: String = "FORGOT_PASSWORD_NEW_PASSWORD_FRAGMENT"
const val CODE_LOG_IN_TO_SIGN_UP: Int = 0
const val CODE_SIGN_UP: Int = 1
const val CODE_SIGN_UP_TO_LOG_IN: Int = 0
const val CODE_LOG_IN: Int = 1
const val TAG_SIGN_UP: String = "SIGN_UP"
const val TAG_LOG_IN: String = "LOG_IN"
const val TAG_FORGOT_PASSWORD_EMAIL = "FORGOT_PASSWORD_EMAIL"
const val TAG_FORGOT_PASSWORD_NEW_PASSWORD = "FORGOT_PASSWORD_NEW_PASSWORD"
const val TAG_EMAIL_VERIFICATION = "EMAIL_VERIFICATION"